// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeatroApi.Data;

#nullable disable

namespace TeatroApi.Data.Migrations
{
    [DbContext(typeof(TeatroContext))]
    [Migration("20240319174928_BBDD6")]
    partial class BBDD6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeatroApi.Models.Asiento", b =>
                {
                    b.Property<int>("AsientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsientoId"));

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<double>("Suplemento")
                        .HasColumnType("float");

                    b.Property<int>("TipoAsiento")
                        .HasColumnType("int");

                    b.HasKey("AsientoId");

                    b.HasIndex("SalaId");

                    b.ToTable("Asientos");

                    b.HasData(
                        new
                        {
                            AsientoId = 1,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 2,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 3,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 4,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 5,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 6,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 7,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 8,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 9,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 10,
                            SalaId = 1,
                            Suplemento = -10.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 11,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 12,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 13,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 14,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 15,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 16,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 17,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 18,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 19,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 20,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 21,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 22,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 23,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 24,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 25,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 26,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 27,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 28,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 29,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 30,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 31,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 32,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 33,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 34,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 35,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 36,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 37,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 38,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 39,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 40,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 41,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 42,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 43,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 44,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 45,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 46,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 47,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 48,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 49,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 50,
                            SalaId = 1,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 51,
                            SalaId = 2,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 52,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 53,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 54,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 55,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 56,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 57,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 58,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 59,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 60,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 61,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 62,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 63,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 64,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 65,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 66,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 67,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 68,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 69,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 70,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 71,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 72,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 73,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 74,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 75,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 76,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 77,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 78,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 79,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 80,
                            SalaId = 2,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 81,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 82,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 83,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 84,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 85,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 86,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 87,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 88,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 89,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 90,
                            SalaId = 3,
                            Suplemento = -10.0,
                            TipoAsiento = 3
                        },
                        new
                        {
                            AsientoId = 91,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 92,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 93,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 94,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 95,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 96,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 97,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 98,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 99,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 100,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 101,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 102,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 103,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 104,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 105,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 106,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 107,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 108,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 109,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 110,
                            SalaId = 3,
                            Suplemento = 0.0,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 111,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 112,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 113,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 114,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 115,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 116,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 117,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 118,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 119,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        },
                        new
                        {
                            AsientoId = 120,
                            SalaId = 3,
                            Suplemento = 20.0,
                            TipoAsiento = 2
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraId"));

                    b.Property<int?>("AsientoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<double>("PrecioCompra")
                        .HasColumnType("float");

                    b.Property<int>("SesionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CompraId");

                    b.HasIndex("AsientoId");

                    b.HasIndex("SesionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras");

                    b.HasData(
                        new
                        {
                            CompraId = 1,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            CompraId = 2,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            CompraId = 3,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            CompraId = 4,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            CompraId = 5,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            CompraId = 6,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            CompraId = 7,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            CompraId = 8,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            CompraId = 9,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            CompraId = 10,
                            PrecioCompra = 0.0,
                            SesionId = 1,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.DetallesCompra", b =>
                {
                    b.Property<int>("SesionId")
                        .HasColumnType("int");

                    b.Property<int>("AsientoId")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.HasKey("SesionId", "AsientoId");

                    b.ToTable("DetallesCompras");

                    b.HasData(
                        new
                        {
                            SesionId = 1,
                            AsientoId = 1,
                            CompraId = 1
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 2,
                            CompraId = 1
                        },
                        new
                        {
                            SesionId = 2,
                            AsientoId = 62,
                            CompraId = 2
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 7,
                            CompraId = 3
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 17,
                            CompraId = 4
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 27,
                            CompraId = 4
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 25,
                            CompraId = 5
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 10,
                            CompraId = 6
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 11,
                            CompraId = 6
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 35,
                            CompraId = 6
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 45,
                            CompraId = 7
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 47,
                            CompraId = 8
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 37,
                            CompraId = 9
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 9,
                            CompraId = 10
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Obra", b =>
                {
                    b.Property<int>("ObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraId"));

                    b.Property<DateTime?>("AuditoriaHorario")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditoriaUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionObra")
                        .HasColumnType("int");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFotoObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraId");

                    b.ToTable("Obras");

                    b.HasData(
                        new
                        {
                            ObraId = 1,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8625),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "Una de las obras más famosas de William Shakespeare, Hamlet es una tragedia que narra la historia del príncipe Hamlet de Dinamarca, quien busca vengar la muerte de su padre a manos de su tío Claudio, que luego se convierte en rey. La obra explora temas como la venganza, la locura, la traición y la corrupción'.",
                            DuracionObra = 180,
                            NombreObra = "Hamlet",
                            RutaFotoObra = "ruta/foto/hamlet.jpg"
                        },
                        new
                        {
                            ObraId = 2,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8677),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "La Casa de Bernarda Alba es una obra de teatro escrita por el dramaturgo español Federico García Lorca. Ambientada en un pueblo de Andalucía, la obra narra la historia de Bernarda Alba, una viuda adinerada y autoritaria que impone un luto riguroso a sus cinco hijas.",
                            DuracionObra = 150,
                            NombreObra = "La Casa de Bernarda Alba",
                            RutaFotoObra = "ruta/foto/bernarda_alba.jpg"
                        },
                        new
                        {
                            ObraId = 3,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8680),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "Romeo y Julieta es una de las tragedias más conocidas de William Shakespeare. La obra cuenta la historia de dos jóvenes amantes cuyas familias, los Montesco y los Capuleto, están enfrentadas. A pesar de los obstáculos que enfrentan, Romeo y Julieta se enamoran apasionadamente y se casan en secreto.",
                            DuracionObra = 160,
                            NombreObra = "Romeo y Julieta",
                            RutaFotoObra = "ruta/foto/romeo_julieta.jpg"
                        },
                        new
                        {
                            ObraId = 4,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8682),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "El Fantasma de la Ópera es un musical de Andrew Lloyd Webber basado en la novela homónima de Gaston Leroux. La historia se desarrolla en la Ópera de París, donde un misterioso fantasma aterroriza a la compañía y se enamora de Christine, una joven cantante.",
                            DuracionObra = 200,
                            NombreObra = "El Fantasma de la Ópera",
                            RutaFotoObra = "ruta/foto/fantasma_opera.jpg"
                        },
                        new
                        {
                            ObraId = 5,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8684),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "Esperando a Godot es una obra de teatro escrita por Samuel Beckett. La obra sigue a dos personajes, Vladimir y Estragón, que esperan la llegada de alguien llamado Godot, pero nunca llega. Mientras esperan, pasan el tiempo conversando, discutiendo y realizando actividades triviales.",
                            DuracionObra = 120,
                            NombreObra = "Esperando a Godot",
                            RutaFotoObra = "ruta/foto/esperando_godot.jpg"
                        },
                        new
                        {
                            ObraId = 6,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8685),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "Macbeth es una tragedia escrita por William Shakespeare. La obra narra la historia de Macbeth, un noble escocés que, incitado por la profecía de tres brujas, asesina al rey Duncan y se convierte en rey de Escocia. Sin embargo, su sed de poder lo lleva a cometer más crímenes, lo que finalmente conduce a su propia destrucción.",
                            DuracionObra = 170,
                            NombreObra = "Macbeth",
                            RutaFotoObra = "ruta/foto/macbeth.jpg"
                        },
                        new
                        {
                            ObraId = 7,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8687),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "Los Miserables es un musical basado en la novela homónima de Victor Hugo. La historia sigue las vidas entrelazadas de varios personajes, incluido Jean Valjean, un exconvicto que busca redención; Javert, un inspector de policía obsesionado con atraparlo; y Cosette, la hija adoptiva de Valjean.",
                            DuracionObra = 210,
                            NombreObra = "Los Miserables",
                            RutaFotoObra = "ruta/foto/los_miserables.jpg"
                        },
                        new
                        {
                            ObraId = 8,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8689),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "Otelo es una tragedia escrita por William Shakespeare. La obra cuenta la historia del moro Otelo, un general veneciano que se casa con Desdémona, una joven veneciana. Sin embargo, su matrimonio es amenazado por la manipulación de Yago, un subordinado celoso de Otelo, que alimenta los celos de Otelo y lo lleva a cometer un acto trágico de violencia. ",
                            DuracionObra = 190,
                            NombreObra = "Otelo",
                            RutaFotoObra = "ruta/foto/otelo.jpg"
                        },
                        new
                        {
                            ObraId = 9,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8691),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "La Gaviota es una obra de teatro escrita por el dramaturgo ruso Anton Chejov. Ambientada en una finca rural en Rusia, la obra sigue las vidas entrelazadas de varios personajes, incluida la famosa actriz Irina Arkádina, su amante Boris Trigorin y el aspirante a escritor Konstantín Tréplev.",
                            DuracionObra = 180,
                            NombreObra = "La Gaviota",
                            RutaFotoObra = "ruta/foto/la_gaviota.jpg"
                        },
                        new
                        {
                            ObraId = 10,
                            AuditoriaHorario = new DateTime(2024, 3, 19, 18, 49, 28, 726, DateTimeKind.Local).AddTicks(8693),
                            AuditoriaUsuario = "Admin",
                            DescripcionObra = "La Opera de los Tres Centavos es una ópera escrita por el dramaturgo alemán Bertolt Brecht, con música de Kurt Weill. Basada en la ópera del siglo XVIII El mendigo ladrón, la obra satiriza la sociedad capitalista y sigue las aventuras del criminal Mackie Messer, también conocido como Mack the Knife.",
                            DuracionObra = 200,
                            NombreObra = "La Opera de los Tres Centavos",
                            RutaFotoObra = "ruta/foto/Fopera_tres_centavos.jpg"
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaId"));

                    b.Property<int>("AsientosMinusvalidos")
                        .HasColumnType("int");

                    b.Property<int>("AsientosNormales")
                        .HasColumnType("int");

                    b.Property<int>("AsientosVip")
                        .HasColumnType("int");

                    b.HasKey("SalaId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaId = 1,
                            AsientosMinusvalidos = 0,
                            AsientosNormales = 50,
                            AsientosVip = 0
                        },
                        new
                        {
                            SalaId = 2,
                            AsientosMinusvalidos = 0,
                            AsientosNormales = 0,
                            AsientosVip = 30
                        },
                        new
                        {
                            SalaId = 3,
                            AsientosMinusvalidos = 10,
                            AsientosNormales = 30,
                            AsientosVip = 10
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Sesion", b =>
                {
                    b.Property<int>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionId"));

                    b.Property<DateTime?>("AuditoriaHorario")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditoriaUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("SesionId");

                    b.HasIndex("ObraId");

                    b.HasIndex("SalaId");

                    b.ToTable("Sesiones");

                    b.HasData(
                        new
                        {
                            SesionId = 1,
                            FechaHora = new DateTime(2024, 4, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 1,
                            Precio = 50.0,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 2,
                            FechaHora = new DateTime(2024, 4, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 2,
                            Precio = 50.0,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 3,
                            FechaHora = new DateTime(2024, 4, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 1,
                            Precio = 50.0,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 4,
                            FechaHora = new DateTime(2024, 4, 4, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 1,
                            Precio = 50.0,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 5,
                            FechaHora = new DateTime(2024, 4, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 3,
                            Precio = 50.0,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 6,
                            FechaHora = new DateTime(2024, 4, 6, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 3,
                            Precio = 50.0,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 7,
                            FechaHora = new DateTime(2024, 4, 7, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 4,
                            Precio = 50.0,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 8,
                            FechaHora = new DateTime(2024, 4, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 4,
                            Precio = 50.0,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 9,
                            FechaHora = new DateTime(2024, 4, 9, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 5,
                            Precio = 50.0,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 10,
                            FechaHora = new DateTime(2024, 4, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 5,
                            Precio = 50.0,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 11,
                            FechaHora = new DateTime(2024, 4, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 6,
                            Precio = 50.0,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 12,
                            FechaHora = new DateTime(2024, 4, 12, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 6,
                            Precio = 50.0,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 13,
                            FechaHora = new DateTime(2024, 4, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 7,
                            Precio = 50.0,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 14,
                            FechaHora = new DateTime(2024, 4, 14, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 7,
                            Precio = 50.0,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 15,
                            FechaHora = new DateTime(2024, 4, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 8,
                            Precio = 50.0,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 16,
                            FechaHora = new DateTime(2024, 4, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 8,
                            Precio = 50.0,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 17,
                            FechaHora = new DateTime(2024, 4, 17, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 9,
                            Precio = 50.0,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 18,
                            FechaHora = new DateTime(2024, 4, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 9,
                            Precio = 50.0,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 19,
                            FechaHora = new DateTime(2024, 4, 19, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 10,
                            Precio = 50.0,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 20,
                            FechaHora = new DateTime(2024, 4, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 10,
                            Precio = 50.0,
                            SalaId = 2
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            EmailUsuario = "default@example.com",
                            NombreUsuario = "Default",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 2,
                            EmailUsuario = "maria@example.com",
                            NombreUsuario = "María",
                            PasswordUsuario = "1234",
                            Rol = "Admin"
                        },
                        new
                        {
                            UsuarioId = 3,
                            EmailUsuario = "carlos@example.com",
                            NombreUsuario = "Carlos",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 4,
                            EmailUsuario = "laura@example.com",
                            NombreUsuario = "Laura",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 5,
                            EmailUsuario = "pedro@example.com",
                            NombreUsuario = "Pedro",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 6,
                            EmailUsuario = "ana@example.com",
                            NombreUsuario = "Ana",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 7,
                            EmailUsuario = "sofia@example.com",
                            NombreUsuario = "Sofía",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 8,
                            EmailUsuario = "david@example.com",
                            NombreUsuario = "David",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 9,
                            EmailUsuario = "lucia@example.com",
                            NombreUsuario = "Lucía",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 10,
                            EmailUsuario = "diego@example.com",
                            NombreUsuario = "Diego",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 11,
                            EmailUsuario = "paula@example.com",
                            NombreUsuario = "Paula",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 12,
                            EmailUsuario = "manuel@example.com",
                            NombreUsuario = "Manuel",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Asiento", b =>
                {
                    b.HasOne("TeatroApi.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("TeatroApi.Models.Compra", b =>
                {
                    b.HasOne("TeatroApi.Models.Asiento", null)
                        .WithMany("Compras")
                        .HasForeignKey("AsientoId");

                    b.HasOne("TeatroApi.Models.Sesion", "Sesion")
                        .WithMany("Compras")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeatroApi.Models.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TeatroApi.Models.Sesion", b =>
                {
                    b.HasOne("TeatroApi.Models.Obra", "Obra")
                        .WithMany("Sesiones")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeatroApi.Models.Sala", "Sala")
                        .WithMany("Sesiones")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("TeatroApi.Models.Asiento", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("TeatroApi.Models.Obra", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("TeatroApi.Models.Sala", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("TeatroApi.Models.Sesion", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("TeatroApi.Models.Usuario", b =>
                {
                    b.Navigation("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
