// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeatroApi.Data;

#nullable disable

namespace TeatroApi.Data.Migrations
{
    [DbContext(typeof(TeatroContext))]
    [Migration("20240306183706_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeatroApi.Models.Asiento", b =>
                {
                    b.Property<int>("AsientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsientoId"));

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAsiento")
                        .HasColumnType("int");

                    b.HasKey("AsientoId");

                    b.HasIndex("SalaId");

                    b.ToTable("Asientos");

                    b.HasData(
                        new
                        {
                            AsientoId = 1,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 2,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 3,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 4,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 5,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 6,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 7,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 8,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 9,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 10,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 11,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 12,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 13,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 14,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 15,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 16,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 17,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 18,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 19,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 20,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 21,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 22,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 23,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 24,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 25,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 26,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 27,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 28,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 29,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 30,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 31,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 32,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 33,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 34,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 35,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 36,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 37,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 38,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 39,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 40,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 41,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 42,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 43,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 44,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 45,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 46,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 47,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 48,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 49,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 50,
                            SalaId = 1,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 51,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 52,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 53,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 54,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 55,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 56,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 57,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 58,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 59,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 60,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 61,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 62,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 63,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 64,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 65,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 66,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 67,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 68,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 69,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 70,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 71,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 72,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 73,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 74,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 75,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 76,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 77,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 78,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 79,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 80,
                            SalaId = 2,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 81,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 82,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 83,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 84,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 85,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 86,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 87,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 88,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 89,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 90,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 91,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 92,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 93,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 94,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 95,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 96,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 97,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 98,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 99,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 100,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 101,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 102,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 103,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 104,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 105,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 106,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 107,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 108,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 109,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 110,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 111,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 112,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 113,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 114,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 115,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 116,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 117,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 118,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 119,
                            SalaId = 3,
                            TipoAsiento = 1
                        },
                        new
                        {
                            AsientoId = 120,
                            SalaId = 3,
                            TipoAsiento = 1
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            NombreCategoria = "Drama"
                        },
                        new
                        {
                            CategoriaId = 2,
                            NombreCategoria = "Comedia"
                        },
                        new
                        {
                            CategoriaId = 3,
                            NombreCategoria = "Romantica"
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Compra", b =>
                {
                    b.Property<int>("SesionId")
                        .HasColumnType("int");

                    b.Property<int>("AsientoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SesionId", "AsientoId", "UsuarioId");

                    b.HasIndex("AsientoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras");

                    b.HasData(
                        new
                        {
                            SesionId = 1,
                            AsientoId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            SesionId = 1,
                            AsientoId = 2,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Obra", b =>
                {
                    b.Property<int>("ObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFotoObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Obras");

                    b.HasData(
                        new
                        {
                            ObraId = 1,
                            CategoriaId = 1,
                            DescripcionObra = "Una tragedia clásica",
                            NombreObra = "Hamlet",
                            RutaFotoObra = "ruta/foto/hamlet.jpg"
                        },
                        new
                        {
                            ObraId = 2,
                            CategoriaId = 2,
                            DescripcionObra = "Un drama familiar",
                            NombreObra = "La Casa de Bernarda Alba",
                            RutaFotoObra = "ruta/foto/bernarda_alba.jpg"
                        },
                        new
                        {
                            ObraId = 3,
                            CategoriaId = 1,
                            DescripcionObra = "Amor prohibido entre dos familias rivales",
                            NombreObra = "Romeo y Julieta",
                            RutaFotoObra = "ruta/foto/romeo_julieta.jpg"
                        },
                        new
                        {
                            ObraId = 4,
                            CategoriaId = 3,
                            DescripcionObra = "Una historia de amor y tragedia en la Ópera de París",
                            NombreObra = "El Fantasma de la Ópera",
                            RutaFotoObra = "ruta/foto/fantasma_opera.jpg"
                        },
                        new
                        {
                            ObraId = 5,
                            CategoriaId = 2,
                            DescripcionObra = "Dos personajes esperan a alguien que nunca llega",
                            NombreObra = "Esperando a Godot",
                            RutaFotoObra = "ruta/foto/esperando_godot.jpg"
                        },
                        new
                        {
                            ObraId = 6,
                            CategoriaId = 1,
                            DescripcionObra = "Una tragedia sobre ambición y traición",
                            NombreObra = "Macbeth",
                            RutaFotoObra = "ruta/foto/macbeth.jpg"
                        },
                        new
                        {
                            ObraId = 7,
                            CategoriaId = 3,
                            DescripcionObra = "La historia de Jean Valjean y su redención",
                            NombreObra = "Los Miserables",
                            RutaFotoObra = "ruta/foto/los_miserables.jpg"
                        },
                        new
                        {
                            ObraId = 8,
                            CategoriaId = 1,
                            DescripcionObra = "Celos y traición en la Venecia del siglo XVI",
                            NombreObra = "Otelo",
                            RutaFotoObra = "ruta/foto/otelo.jpg"
                        },
                        new
                        {
                            ObraId = 9,
                            CategoriaId = 2,
                            DescripcionObra = "Drama de amor y desilusión en la sociedad rusa del siglo XIX",
                            NombreObra = "La Gaviota",
                            RutaFotoObra = "ruta/foto/la_gaviota.jpg"
                        },
                        new
                        {
                            ObraId = 10,
                            CategoriaId = 3,
                            DescripcionObra = "Una ópera sobre el crimen y la pobreza en Londres",
                            NombreObra = "La Opera de los Tres Centavos",
                            RutaFotoObra = "ruta/foto/Fopera_tres_centavos.jpg"
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaId"));

                    b.HasKey("SalaId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaId = 1
                        },
                        new
                        {
                            SalaId = 2
                        },
                        new
                        {
                            SalaId = 3
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Sesion", b =>
                {
                    b.Property<int>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionId"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("SesionId");

                    b.HasIndex("ObraId");

                    b.HasIndex("SalaId");

                    b.ToTable("Sesiones");

                    b.HasData(
                        new
                        {
                            SesionId = 1,
                            FechaHora = new DateTime(2024, 4, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 1,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 2,
                            FechaHora = new DateTime(2024, 4, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 2,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 3,
                            FechaHora = new DateTime(2024, 4, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 1,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 4,
                            FechaHora = new DateTime(2024, 4, 4, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 1,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 5,
                            FechaHora = new DateTime(2024, 4, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 3,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 6,
                            FechaHora = new DateTime(2024, 4, 6, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 3,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 7,
                            FechaHora = new DateTime(2024, 4, 7, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 4,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 8,
                            FechaHora = new DateTime(2024, 4, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 4,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 9,
                            FechaHora = new DateTime(2024, 4, 9, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 5,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 10,
                            FechaHora = new DateTime(2024, 4, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 5,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 11,
                            FechaHora = new DateTime(2024, 4, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 6,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 12,
                            FechaHora = new DateTime(2024, 4, 12, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 6,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 13,
                            FechaHora = new DateTime(2024, 4, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 7,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 14,
                            FechaHora = new DateTime(2024, 4, 14, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 7,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 15,
                            FechaHora = new DateTime(2024, 4, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 8,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 16,
                            FechaHora = new DateTime(2024, 4, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 8,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 17,
                            FechaHora = new DateTime(2024, 4, 17, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 9,
                            SalaId = 2
                        },
                        new
                        {
                            SesionId = 18,
                            FechaHora = new DateTime(2024, 4, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 9,
                            SalaId = 3
                        },
                        new
                        {
                            SesionId = 19,
                            FechaHora = new DateTime(2024, 4, 19, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 10,
                            SalaId = 1
                        },
                        new
                        {
                            SesionId = 20,
                            FechaHora = new DateTime(2024, 4, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ObraId = 10,
                            SalaId = 2
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            EmailUsuario = "juan@example.com",
                            NombreUsuario = "Juan",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 2,
                            EmailUsuario = "maria@example.com",
                            NombreUsuario = "María",
                            PasswordUsuario = "1234",
                            Rol = "Admin"
                        },
                        new
                        {
                            UsuarioId = 3,
                            EmailUsuario = "carlos@example.com",
                            NombreUsuario = "Carlos",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 4,
                            EmailUsuario = "laura@example.com",
                            NombreUsuario = "Laura",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 5,
                            EmailUsuario = "pedro@example.com",
                            NombreUsuario = "Pedro",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 6,
                            EmailUsuario = "ana@example.com",
                            NombreUsuario = "Ana",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 7,
                            EmailUsuario = "sofia@example.com",
                            NombreUsuario = "Sofía",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 8,
                            EmailUsuario = "david@example.com",
                            NombreUsuario = "David",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 9,
                            EmailUsuario = "lucia@example.com",
                            NombreUsuario = "Lucía",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 10,
                            EmailUsuario = "diego@example.com",
                            NombreUsuario = "Diego",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 11,
                            EmailUsuario = "paula@example.com",
                            NombreUsuario = "Paula",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        },
                        new
                        {
                            UsuarioId = 12,
                            EmailUsuario = "manuel@example.com",
                            NombreUsuario = "Manuel",
                            PasswordUsuario = "1234",
                            Rol = "Guest"
                        });
                });

            modelBuilder.Entity("TeatroApi.Models.Asiento", b =>
                {
                    b.HasOne("TeatroApi.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("TeatroApi.Models.Compra", b =>
                {
                    b.HasOne("TeatroApi.Models.Asiento", "Asiento")
                        .WithMany("Compras")
                        .HasForeignKey("AsientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeatroApi.Models.Sesion", "Sesion")
                        .WithMany("Compras")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TeatroApi.Models.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Sesion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TeatroApi.Models.Obra", b =>
                {
                    b.HasOne("TeatroApi.Models.Categoria", "Categoria")
                        .WithMany("Obras")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TeatroApi.Models.Sesion", b =>
                {
                    b.HasOne("TeatroApi.Models.Obra", "Obra")
                        .WithMany("Sesiones")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeatroApi.Models.Sala", "Sala")
                        .WithMany("Sesiones")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("TeatroApi.Models.Asiento", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("TeatroApi.Models.Categoria", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("TeatroApi.Models.Obra", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("TeatroApi.Models.Sala", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("TeatroApi.Models.Sesion", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("TeatroApi.Models.Usuario", b =>
                {
                    b.Navigation("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
