apiVersion: v1
kind: Service
metadata:
  name: dotnetapi
  labels:
    app: dotnetapi
spec:
  ports:
    - port: 80
  selector:
    app: dotnetapi
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dotnetapi
  labels:
    app: dotnetapi
spec:
  selector:
    matchLabels:
      app: dotnetapi
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dotnetapi
        tier: frontend
    spec:
      containers:
      - name: apiteatro
        image: a24958/teatro-api:v2.5
        ports:
        - containerPort: 80
