apiVersion: v1
kind: Service
metadata:
  labels:
    app: sql-server
  name: sql-server
spec:
  externalName: galactic1.czprnk7ohtvk.us-east-1.rds.amazonaws.com
  selector:
    app: sql-server
  type: ExternalName
status:
  loadBalancer: {}
